'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'ta';
  setLanguage: (lang: 'en' | 'ta') => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.events': 'Events',
    'nav.sermons': 'Sermons',
    'nav.prayer': 'Prayer',
    'nav.gallery': 'Gallery',
    'nav.blog': 'Blog',
    'nav.smallGroups': 'Small Groups',
    'nav.testimonials': 'Testimonials',
    'nav.resources': 'Resources',
    'nav.contact': 'Contact',
    'nav.give': 'Give',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.register': 'Register',
    'nav.ministries': 'Ministries',
    'nav.community': 'Community',
    'nav.announcements': 'News',
    'nav.more': 'More',
    'nav.getInvolved': 'Get Involved',
    'nav.connect': 'Connect',
    'nav.profile': 'My Profile',
    'nav.dashboard': 'Dashboard',
    'nav.toggleTheme': 'Toggle Theme',
    'nav.tagline': 'Faith • Hope • Love',
    
    // About submenu
    'nav.beliefs': 'Our Beliefs',
    'nav.branches': 'Our Branches', 
    'nav.pastors': 'Our Pastors',
    'nav.history': 'Our History',
    
    // Ministries submenu
    'nav.allMinistries': 'All Ministries',
    'nav.children': 'Children',
    'nav.youth': 'Youth',
    'nav.adults': 'Adults',
    
    // Home Page
    'home.welcome': 'Welcome to Salem Primitive Baptist Church',
    'home.subtitle': 'A place of faith, hope, and love',
    'home.liveStream': 'Live Stream',
    'home.upcomingEvents': 'Upcoming Events',
    'home.latestSermons': 'Latest Sermons',
    'home.joinUs': 'Join Us',
    'home.learnMore': 'Learn More',
    'home.watchLive': 'Watch Live',
    'home.ourMission': 'Our Mission',
    'home.ourVision': 'Our Vision',
    'home.ourValues': 'Our Values',
    
    // Services
    'services.wedding': 'Wedding',
    'services.baptism': 'Baptism',
    'services.request': 'Request Service',
    'services.title': 'Our Services',
    'services.description': 'We offer various services to serve our community',
    'services.schedule': 'Service Schedule',
    'services.sunday': 'Sunday Service',
    'services.prayer': 'Prayer Meeting',
    'services.bible': 'Bible Study',
    
    // Events
    'events.title': 'Upcoming Events',
    'events.noEvents': 'No upcoming events',
    'events.viewAll': 'View All Events',
    'events.register': 'Register',
    'events.details': 'Event Details',
    'events.date': 'Date',
    'events.time': 'Time',
    'events.location': 'Location',
    
    // Forms
    'form.firstName': 'First Name',
    'form.lastName': 'Last Name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.message': 'Message',
    'form.submit': 'Submit',
    'form.required': 'Required',
    'form.optional': 'Optional',
    'form.sending': 'Sending...',
    'form.sent': 'Message Sent',
    'form.error': 'Error sending message',
    
    // Donations
    'donations.history': 'Donation History',
    'donations.amount': 'Amount',
    'donations.date': 'Date',
    'donations.type': 'Type',
    'donations.status': 'Status',
    'donations.receipt': 'Receipt',
    'donations.total': 'Total Donated',
    'donations.donate': 'Donate Now',
    'donations.oneTime': 'One-time',
    'donations.monthly': 'Monthly',
    'donations.thank': 'Thank you for your generosity',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.readMore': 'Read More',
    'common.showLess': 'Show Less',

    // Home Page — static section chrome (dynamic CMS content like
    // announcement/sermon/event bodies is intentionally NOT covered here,
    // see Phase G scope note in the gap-fix plan)
    'home.weekAtGlance': 'This Week at a Glance',
    'home.latestAnnouncements': 'Latest Announcements',
    'home.connectWithUs': 'Connect With Us',
    'home.quickJoinTitle': 'Join Us Sunday',
    'home.quickJoinDesc': 'Worship with us every Sunday at 9:30 AM',
    'home.quickGiveTitle': 'Give',
    'home.quickGiveDesc': 'See how to support our mission',
    'home.quickPrayerTitle': 'Prayer Request',
    'home.quickPrayerDesc': 'Share your prayer needs with our community',
    'home.quickContactTitle': 'Get In Touch',
    'home.quickContactDesc': 'Contact us with questions or to learn more',
    'home.recentSermons': 'Recent Sermons',
    'home.browseAllSermons': 'Browse all sermons',
    'home.testimonialsHeading': 'What Our Church Family Says',
    'home.fromBlog': 'From the Blog',
    'home.galleryHeading': 'Gallery',
    'home.viewGallery': 'View Gallery',
    'home.needPrayerHeading': 'Need Prayer?',
    'home.needPrayerBody': "Our community would be honored to pray with and for you. Share your request — as public or private as you'd like.",
    'home.submitPrayerRequest': 'Submit a Prayer Request',
    'home.stayInLoop': 'Stay in the loop',
    'home.newsletterBlurb': 'Announcements and updates, straight to your inbox.',
    'home.nextService': 'Next Service',
    'home.defaultServiceFallback': 'Sunday Worship — 9:30 AM',
    'home.viewServiceTimes': 'View all service times',
    'home.liveNowTap': 'Live now — tap to watch',
    'auth.signIn': 'Sign In',
    'home.myDashboard': 'My Dashboard',
    'home.joinSundayCta': 'Join Us Sunday 9:30 AM',

    // Live stream chrome, reused across pages that offer a watch-live toggle
    'liveStream.watchButton': 'Watch Live Stream',
    'liveStream.noneCurrently': 'No Live Stream Currently',

    // Services page — static chrome only; the CMS-authored service/event
    // copy itself is out of scope for this static dictionary (see Phase G
    // scope note)
    'services.eyebrow': 'Worship With Us',
    'services.nav.serviceTimes': 'Service Times',
    'services.nav.whatToExpect': 'What to Expect',
    'services.nav.specialEvents': 'Special Events',
    'services.nav.onlineServices': 'Online Services',
    'services.nav.planYourVisit': 'Plan Your Visit',
    'services.addToCalendar': 'Add to Calendar',
    'services.whatToExpectSubtitle': "Your first visit made easy — here's what you can expect when you join us",
    'services.specialEventsSubtitle': 'Join us for these special worship experiences throughout the year',
    'services.watchOnYouTube': 'Watch on YouTube',
    'services.joinViaZoom': 'Join via Zoom',
    'services.getNotifications': 'Get Notifications',
    'services.liveStreamAvailable': 'Live Stream Available',
    'services.nextService': 'Next service:',
    'services.checkScheduleForTimes': 'Check schedule for times',
    'services.contactUs': 'Contact Us',
    'services.getDirections': 'Get Directions',
    'services.notFoundTitle': 'Services page content not found',
    'services.notFoundDescription': 'Please add content through the admin panel',
    'services.loading': 'Loading services...',

    // Contact page — page-level chrome and the multi-step form's structural
    // text (step indicator, nav buttons, submit banners). The long tail of
    // conditional form-field labels/options (address, gender, baptism type,
    // volunteer areas, etc.) is intentionally out of scope for this pass —
    // flagged rather than silently machine-translated, see Phase G scope note.
    'contact.loading': 'Loading contact information...',
    'contact.eyebrow': 'Get In Touch',
    'contact.title': 'Contact Us',
    'contact.description': "We'd love to hear from you. Get in touch with our church family.",
    'contact.sendMessage': 'Send us a Message',
    'contact.stepOf': 'Step {n} of 3:',
    'contact.stepPersonal': 'Personal Information',
    'contact.stepCategory': 'Category Selection',
    'contact.stepDetails': 'Details & Message',
    'contact.category': 'Category',
    'contact.specificRequest': 'Specific Request',
    'contact.selectRequestType': 'Select request type',
    'contact.expectedResponseTime': 'Expected response time:',
    'contact.routedTo': 'This will be routed to',
    'contact.previous': 'Previous',
    'contact.next': 'Next',
    'contact.sendMessageBtn': 'Send Message',
    'contact.submitSuccess': "Thank you for your message! We'll get back to you soon.",
    'contact.submitError': 'Something went wrong sending your message. Please try again, or reach us directly using the contact details on this page.',
    'contact.getInTouch': 'Get in Touch',
    'contact.getInTouchBody': "Whether you're looking for information about our services, want to get involved, or need prayer, we're here for you. Don't hesitate to reach out!",
    'contact.addressLabel': 'Address',
    'contact.addressUnavailable': 'Address not available',
    'contact.phoneLabel': 'Phone',
    'contact.phoneUnavailable': 'Phone not available',
    'contact.emailLabel': 'Email',
    'contact.emailUnavailable': 'Email not available',
    'contact.officeHoursLabel': 'Office Hours',
    'contact.officeHoursUnavailable': 'Contact us for availability',
    'contact.quickActions': 'Quick Actions',
    'contact.scheduleMeeting': 'Schedule a Meeting',
    'contact.submitPrayerRequest': 'Submit Prayer Request',
    'contact.getDirections': 'Get Directions',
    'contact.joinWhatsApp': 'Join WhatsApp Group',
    'contact.ourStaff': 'Our Staff',
    'contact.ourStaffSubtitle': 'Meet our dedicated team who are here to serve you',
    'contact.faqHeading': 'Contact FAQ',
    'contact.findUs': 'Find Us',
    'contact.findUsSubtitle': 'Visit us at our location',
    'contact.category.spiritual': 'Spiritual & Community Life',
    'contact.category.administrative': 'Administrative & Facility',
    'contact.category.media': 'Media & Communication',
    'contact.category.outreach': 'Outreach & Missions',
    'contact.faq.responseTime.q': 'How quickly will I hear back?',
    'contact.faq.responseTime.a': 'It depends on the type of request — typically 1-5 business days. Prayer requests marked urgent or emergency are prioritized and answered as soon as possible.',
    'contact.faq.whoResponds.q': 'Who will respond to my message?',
    'contact.faq.whoResponds.a': 'Your message is routed based on the category you select, so it reaches the staff member or ministry team best equipped to help.',
    'contact.faq.urgent.q': 'What if my need is urgent?',
    'contact.faq.urgent.a': 'For a pastoral emergency, please call the church office directly rather than submitting the form — phone reaches us faster than email.',
    'contact.faq.visit.q': 'Can I just stop by instead of submitting a form?',
    'contact.faq.visit.a': "Absolutely — our office hours are listed on this page. You're always welcome to visit or call directly.",

    // Prayer page — page chrome and prayer-wall UI; individual prayer
    // request bodies are user-submitted content, not translated
    'prayer.eyebrow': 'Prayer Wall',
    'prayer.title': 'Prayer Requests',
    'prayer.description': 'Share your prayer needs and join us in lifting each other up',
    'prayer.submitRequest': 'Submit Prayer Request',
    'prayer.wallTab': 'Prayer Wall',
    'prayer.answeredTab': 'Answered Prayers',
    'prayer.allPrayers': 'All Prayers',
    'prayer.category.healing': 'Healing',
    'prayer.category.guidance': 'Guidance',
    'prayer.category.thanksgiving': 'Thanksgiving',
    'prayer.category.family': 'Family',
    'prayer.category.work': 'Work',
    'prayer.category.general': 'General',
    'prayer.loading': 'Loading prayer requests...',
    'prayer.noAnsweredYet': 'No answered prayers yet',
    'prayer.noRequestsYet': 'No prayer requests yet',
    'prayer.checkBackAnswered': 'Check back soon to celebrate what God has done.',
    'prayer.submitToStart': 'Submit a prayer request to get started',
    'prayer.ongoing': 'Ongoing',
    'prayer.answered': 'Answered',
    'prayer.anonymous': 'Anonymous',
    'prayer.imPraying': "I'm Praying",
    'prayer.prayForThis': 'Pray for This',
    'prayer.prayed': 'prayed',
    'prayer.statRequests': 'Prayer Requests',
    'prayer.statPeople': 'People Praying',
    'prayer.statPrayers': 'Prayers Offered',
    'prayer.modalTitle': 'Submit Prayer Request',
    'prayer.prayerTitleLabel': 'Prayer Title',
    'prayer.prayerTitlePlaceholder': 'Enter a title for your prayer request',
    'prayer.requestLabel': 'Prayer Request',
    'prayer.requestPlaceholder': 'Share your prayer request...',
    'prayer.submitAnonymously': 'Submit anonymously',
    'prayer.yourNameOptional': 'Your name (optional)',
    'prayer.keepPrivate': 'Keep this prayer private (only pastors will see it)',
    'prayer.requestFollowUp': 'Request a private follow-up check-in in about a week',
    'prayer.emailForFollowUp': 'Your email for the follow-up',
    'prayer.cancel': 'Cancel',
    'prayer.submitPrayer': 'Submit Prayer',
    'prayer.powerOfPrayer': 'The Power of Prayer',
    'prayer.verseQuote': '"Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours."',
    'prayer.verseCitation': 'Mark 11:24',
    'prayer.powerBody': 'We believe in the power of prayer and the strength that comes from praying together as a community. Your prayers matter, and we are honored to lift each other up before God.',

    // Give page — static chrome; givingFunds/GIVING_FAQ/WHY_GIVE/impact area
    // copy is hardcoded UI content (not CMS), translated in full below
    'give.eyebrow': 'Generosity',
    'give.title': 'Give with Joy',
    'give.description': "Your generosity helps us serve our community and spread God's love",
    'give.waysToGive': 'Ways to Give',
    'give.waysToGiveSubtitle': "Online giving isn't available on the website yet. Here's how to give today:",
    'give.bankTransferTitle': 'Bank Transfer',
    'give.bankTransferBodyPrefix': 'Account details are available directly from the church office — please',
    'give.call': 'call',
    'give.or': 'or',
    'give.contactUs': 'contact us',
    'give.bankTransferBodySuffix': "and we'll share transfer instructions.",
    'give.inPersonTitle': 'In Person',
    'give.inPersonBody': 'Give during any of our worship services — see our current service times for when to join us.',
    'give.viewServiceTimes': 'View Service Times',
    'give.questionsTitle': 'Questions?',
    'give.questionsBody': 'Reach out about recurring gifts, planned/legacy giving, or designating a gift to a specific fund below.',
    'give.contactUsArrow': 'Contact Us',
    'give.designateHeading': 'You Can Designate Your Gift To',
    'give.designateSubtitle': 'Select a fund to see what to mention when you give.',
    'give.designateSelected': 'When you give, mention',
    'give.designateSelectedSuffix': 'so your gift is designated correctly.',
    'give.designateHint': "Just let us know which fund you'd like to support when you give in person or transfer a gift.",
    'give.fund.tithe.title': 'Tithe & Offerings',
    'give.fund.tithe.description': 'Regular giving to support our church ministries and operations',
    'give.fund.missions.title': 'Missions Fund',
    'give.fund.missions.description': 'Support our global mission work and local outreach programs',
    'give.fund.building.title': 'Building Fund',
    'give.fund.building.description': 'Help us maintain and improve our church facilities',
    'give.fund.special.title': 'Special Projects',
    'give.fund.special.description': 'Support specific ministry projects and community initiatives',
    'give.yourImpact': 'Your Impact',
    'give.yourImpactSubtitle': 'See how your generosity is making a difference in our community',
    'give.raisedThisYear': 'raised this year',
    'give.godsProvision': "God's provision",
    'give.impact.community.title': 'Community Outreach',
    'give.impact.community.description': 'Supporting families in need through food drives, counseling, and assistance programs.',
    'give.impact.missions.title': 'Global Missions',
    'give.impact.missions.description': 'Spreading the Gospel worldwide through missionary support and evangelism.',
    'give.impact.education.title': 'Education Ministry',
    'give.impact.education.description': 'Providing quality Christian education and scholarship programs.',
    'give.impact.youth.title': 'Youth Programs',
    'give.impact.youth.description': 'Investing in the next generation through camps, mentorship, and activities.',
    'give.transparencyHeading': 'Transparency Report',
    'give.transparencySubtitle': 'A look at how gifts are stewarded',
    'give.transparency.ministry': 'Ministry',
    'give.transparency.operations': 'Operations',
    'give.transparency.missions': 'Missions',
    'give.transparency.building': 'Building',
    'give.downloadAnnualReport': 'Download Annual Report',
    'give.whyWeGive': 'Why We Give',
    'give.why.worship.title': 'Worship Through Giving',
    'give.why.worship.description': 'Giving is an act of worship that acknowledges God as the source of all blessings.',
    'give.why.support.title': 'Support Our Mission',
    'give.why.support.description': 'Your gifts enable us to serve our community and spread the Gospel effectively.',
    'give.why.difference.title': 'Make a Difference',
    'give.why.difference.description': "Together, we can transform lives and communities through God's love and grace.",
    'give.verseQuote': '"Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver."',
    'give.verseCitation': '2 Corinthians 9:7',
    'give.faqHeading': 'Giving FAQ',
    'give.faq.receipt.q': 'Will I receive a giving receipt?',
    'give.faq.receipt.a': "Yes — contact the church office with your gift details and we'll provide a receipt for your records, including for tax purposes.",
    'give.faq.recurring.q': 'Can I set up recurring giving?',
    'give.faq.recurring.a': 'Yes, through a standing bank transfer instruction with your bank, or by arranging a recurring in-person gift with the church office. Ask us for guidance when you reach out.',
    'give.faq.designate.q': 'How do I make sure my gift goes to a specific fund?',
    'give.faq.designate.a': 'Select a fund below to see the name to reference, then mention it when you give in person or note it on your bank transfer.',
    'give.faq.method.q': "What's the difference between bank transfer and giving in person?",
    'give.faq.method.a': 'Both are fully counted the same way — bank transfer is convenient between services, while giving in person lets you use envelopes the office already tracks. Choose whichever is easiest for you.',
    'give.faq.legacy.q': 'What is planned or legacy giving?',
    'give.faq.legacy.aPrefix': 'A way to include the church in your will, trust, or beneficiary designations. See our',
    'give.faq.legacy.aLink': 'Legacy Giving page',
    'give.faq.legacy.aSuffix': 'for details.',
    'give.legacyTitle': 'Planned & Legacy Giving',
    'give.legacyBody': 'Include the church in your will, trust, or estate plans to leave a lasting legacy of generosity.',
    'give.learnAboutLegacy': 'Learn About Legacy Giving',
    'give.questionsAboutGiving': 'Questions About Giving?',
    'give.questionsAboutGivingBody': "We're here to help you with your generosity journey",
    'give.contactUsBtn': 'Contact Us',

    // About/Beliefs page — static chrome and default fallback copy (used
    // only when the CMS 'about' page content doesn't exist yet); the
    // CMS-authored beliefs/values/FAQ content itself is out of scope
    'about.eyebrow': 'About Us',
    'about.breadcrumbAbout': 'About',
    'about.breadcrumbBeliefs': 'Beliefs',
    'about.defaultTitle': 'Our Beliefs & About Us',
    'about.defaultSubtitle': 'Learn about our church family and what we believe',
    'about.nav.missionVision': 'Mission & Vision',
    'about.nav.coreValues': 'Core Values',
    'about.nav.whatWeBelieve': 'What We Believe',
    'about.nav.faq': 'FAQ',
    'about.ourMission': 'Our Mission',
    'about.defaultMission': 'To proclaim the Gospel of Jesus Christ, nurture believers through sound teaching, and build a community grounded in grace, faith, and love.',
    'about.ourVision': 'Our Vision',
    'about.defaultVision': 'To be a Christ-centered church that transforms lives and communities through faith, love, and service — equipping every believer to live with purpose.',
    'about.defaultCoreValues': 'Core Values',
    'about.defaultWhatWeBelieve': 'What We Believe',
    'about.guidingScripture': 'Guiding Scripture',
    'about.faqHeading': 'Frequently Asked Questions',
    'about.faq.visit.q': 'What should I expect when visiting for the first time?',
    'about.faq.visit.a': "A warm welcome, congregational singing, prayer, and expository preaching from Scripture. Services typically run about 90 minutes, and there's no dress code — come as you are.",
    'about.faq.baptism.q': 'Do you baptize infants or only believers?',
    'about.faq.baptism.a': "We practice believer's baptism by immersion, following a personal profession of faith, in keeping with our Primitive Baptist convictions.",
    'about.faq.children.q': 'Is there a place for my children during the service?',
    'about.faq.children.a': "Children are welcome to worship alongside their families. Reach out to a greeter when you arrive and they'll point you to any age-appropriate provisions we have that day.",
    'about.faq.membership.q': 'How can I become a member?',
    'about.faq.membership.a': "Membership follows a profession of faith and believer's baptism, along with meeting our pastors. Speak with one of our pastors after a service or use the Contact page to start the conversation."
  },
  ta: {
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.services': 'சேவைகள்',
    'nav.events': 'நிகழ்வுகள்',
    'nav.sermons': 'பிரசங்கங்கள்',
    'nav.prayer': 'ஜெபம்',
    'nav.gallery': 'படக்காட்சி',
    'nav.blog': 'வலைப்பதிவு',
    'nav.smallGroups': 'சிறு குழுக்கள்',
    'nav.testimonials': 'சாட்சிகள்',
    'nav.resources': 'வளங்கள்',
    'nav.contact': 'தொடர்பு',
    'nav.give': 'நன்கொடை',
    'nav.login': 'உள்நுழைவு',
    'nav.logout': 'வெளியேறு',
    'nav.register': 'பதிவு செய்யவும்',
    'nav.ministries': 'ஊழியங்கள்',
    'nav.community': 'சமூகம்',
    'nav.announcements': 'செய்திகள்',
    'nav.more': 'மேலும்',
    'nav.getInvolved': 'ஈடுபடுங்கள்',
    'nav.connect': 'இணையுங்கள்',
    'nav.profile': 'என் சுயவிவரம்',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.toggleTheme': 'தீம் மாற்று',
    'nav.tagline': 'நம்பிக்கை • நம்பிக்கை • அன்பு',
    
    // About submenu
    'nav.beliefs': 'எங்கள் நம்பிக்கைகள்',
    'nav.branches': 'எங்கள் கிளைகள்',
    'nav.pastors': 'எங்கள் போதகர்கள்',
    'nav.history': 'எங்கள் வரலாறு',
    
    // Ministries submenu
    'nav.allMinistries': 'அனைத்து ஊழியங்கள்',
    'nav.children': 'குழந்தைகள்',
    'nav.youth': 'இளைஞர்கள்',
    'nav.adults': 'பெரியவர்கள்',
    
    // Home Page
    'home.welcome': 'சேலம் பிரிமிட்டிவ் பாப்டிஸ்ட் தேவாலயத்திற்கு வரவேற்கிறோம்',
    'home.subtitle': 'நம்பிக்கை, நம்பிக்கை மற்றும் அன்பின் இடம்',
    'home.liveStream': 'நேரடி ஒளிபரப்பு',
    'home.upcomingEvents': 'வரவிருக்கும் நிகழ்வுகள்',
    'home.latestSermons': 'சமீபத்திய பிரசங்கங்கள்',
    'home.joinUs': 'எங்களுடன் சேரவும்',
    'home.learnMore': 'மேலும் அறிக',
    'home.watchLive': 'நேரடி பார்க்க',
    'home.ourMission': 'எங்கள் நோக்கம்',
    'home.ourVision': 'எங்கள் பார்வை',
    'home.ourValues': 'எங்கள் மதிப்புகள்',
    
    // Services
    'services.wedding': 'திருமணம்',
    'services.baptism': 'ஞானஸ்நானம்',
    'services.request': 'சேவை கோரிக்கை',
    'services.title': 'எங்கள் சேவைகள்',
    'services.description': 'எங்கள் சமூகத்திற்கு சேவை செய்ய பல்வேறு சேவைகளை வழங்குகிறோம்',
    'services.schedule': 'சேவை அட்டவணை',
    'services.sunday': 'ஞாயிறு சேவை',
    'services.prayer': 'ஜெப கூட்டம்',
    'services.bible': 'பைபிள் படிப்பு',
    
    // Events
    'events.title': 'வரவிருக்கும் நிகழ்வுகள்',
    'events.noEvents': 'வரவிருக்கும் நிகழ்வுகள் இல்லை',
    'events.viewAll': 'அனைத்து நிகழ்வுகளையும் பார்க்க',
    'events.register': 'பதிவு செய்யவும்',
    'events.details': 'நிகழ்வு விவரங்கள்',
    'events.date': 'தேதி',
    'events.time': 'நேரம்',
    'events.location': 'இடம்',
    
    // Forms
    'form.firstName': 'முதல் பெயர்',
    'form.lastName': 'கடைசி பெயர்',
    'form.email': 'மின்னஞ்சல்',
    'form.phone': 'தொலைபேசி',
    'form.message': 'செய்தி',
    'form.submit': 'சமர்ப்பிக்கவும்',
    'form.required': 'தேவையான',
    'form.optional': 'விருப்பமான',
    'form.sending': 'அனுப்புகிறது...',
    'form.sent': 'செய்தி அனுப்பப்பட்டது',
    'form.error': 'செய்தி அனுப்புவதில் பிழை',
    
    // Donations
    'donations.history': 'நன்கொடை வரலாறு',
    'donations.amount': 'தொகை',
    'donations.date': 'தேதி',
    'donations.type': 'வகை',
    'donations.status': 'நிலை',
    'donations.receipt': 'ரசீது',
    'donations.total': 'மொத்த நன்கொடை',
    'donations.donate': 'இப்போது நன்கொடை',
    'donations.oneTime': 'ஒரு முறை',
    'donations.monthly': 'மாதாந்திர',
    'donations.thank': 'உங்கள் தாராள மனதிற்கு நன்றி',
    
    // Common
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'பிழை',
    'common.success': 'வெற்றி',
    'common.cancel': 'ரத்து செய்',
    'common.save': 'சேமி',
    'common.edit': 'திருத்து',
    'common.delete': 'நீக்கு',
    'common.search': 'தேடு',
    'common.filter': 'வடிகட்டி',
    'common.all': 'அனைத்தும்',
    'common.yes': 'ஆம்',
    'common.no': 'இல்லை',
    'common.close': 'மூடு',
    'common.open': 'திற',
    'common.back': 'பின்',
    'common.next': 'அடுத்து',
    'common.previous': 'முந்தைய',
    'common.readMore': 'மேலும் படிக்க',
    'common.showLess': 'குறைவாக காட்டு',

    // Home Page — TODO: verify translation. Placeholder English text below,
    // not yet translated by a Tamil speaker — see Phase G scope note.
    'home.weekAtGlance': 'This Week at a Glance',
    'home.latestAnnouncements': 'Latest Announcements',
    'home.connectWithUs': 'Connect With Us',
    'home.quickJoinTitle': 'Join Us Sunday',
    'home.quickJoinDesc': 'Worship with us every Sunday at 9:30 AM',
    'home.quickGiveTitle': 'Give',
    'home.quickGiveDesc': 'See how to support our mission',
    'home.quickPrayerTitle': 'Prayer Request',
    'home.quickPrayerDesc': 'Share your prayer needs with our community',
    'home.quickContactTitle': 'Get In Touch',
    'home.quickContactDesc': 'Contact us with questions or to learn more',
    'home.recentSermons': 'Recent Sermons',
    'home.browseAllSermons': 'Browse all sermons',
    'home.testimonialsHeading': 'What Our Church Family Says',
    'home.fromBlog': 'From the Blog',
    'home.galleryHeading': 'Gallery',
    'home.viewGallery': 'View Gallery',
    'home.needPrayerHeading': 'Need Prayer?',
    'home.needPrayerBody': "Our community would be honored to pray with and for you. Share your request — as public or private as you'd like.",
    'home.submitPrayerRequest': 'Submit a Prayer Request',
    'home.stayInLoop': 'Stay in the loop',
    'home.newsletterBlurb': 'Announcements and updates, straight to your inbox.',
    'home.nextService': 'Next Service',
    'home.defaultServiceFallback': 'Sunday Worship — 9:30 AM',
    'home.viewServiceTimes': 'View all service times',
    'home.liveNowTap': 'Live now — tap to watch',
    'auth.signIn': 'Sign In',
    'home.myDashboard': 'My Dashboard',
    'home.joinSundayCta': 'Join Us Sunday 9:30 AM',

    // Live stream chrome — TODO: verify translation
    'liveStream.watchButton': 'Watch Live Stream',
    'liveStream.noneCurrently': 'No Live Stream Currently',

    // Services page — TODO: verify translation
    'services.eyebrow': 'Worship With Us',
    'services.nav.serviceTimes': 'Service Times',
    'services.nav.whatToExpect': 'What to Expect',
    'services.nav.specialEvents': 'Special Events',
    'services.nav.onlineServices': 'Online Services',
    'services.nav.planYourVisit': 'Plan Your Visit',
    'services.addToCalendar': 'Add to Calendar',
    'services.whatToExpectSubtitle': "Your first visit made easy — here's what you can expect when you join us",
    'services.specialEventsSubtitle': 'Join us for these special worship experiences throughout the year',
    'services.watchOnYouTube': 'Watch on YouTube',
    'services.joinViaZoom': 'Join via Zoom',
    'services.getNotifications': 'Get Notifications',
    'services.liveStreamAvailable': 'Live Stream Available',
    'services.nextService': 'Next service:',
    'services.checkScheduleForTimes': 'Check schedule for times',
    'services.contactUs': 'Contact Us',
    'services.getDirections': 'Get Directions',
    'services.notFoundTitle': 'Services page content not found',
    'services.notFoundDescription': 'Please add content through the admin panel',
    'services.loading': 'Loading services...',

    // Contact page — TODO: verify translation
    'contact.loading': 'Loading contact information...',
    'contact.eyebrow': 'Get In Touch',
    'contact.title': 'Contact Us',
    'contact.description': "We'd love to hear from you. Get in touch with our church family.",
    'contact.sendMessage': 'Send us a Message',
    'contact.stepOf': 'Step {n} of 3:',
    'contact.stepPersonal': 'Personal Information',
    'contact.stepCategory': 'Category Selection',
    'contact.stepDetails': 'Details & Message',
    'contact.category': 'Category',
    'contact.specificRequest': 'Specific Request',
    'contact.selectRequestType': 'Select request type',
    'contact.expectedResponseTime': 'Expected response time:',
    'contact.routedTo': 'This will be routed to',
    'contact.previous': 'Previous',
    'contact.next': 'Next',
    'contact.sendMessageBtn': 'Send Message',
    'contact.submitSuccess': "Thank you for your message! We'll get back to you soon.",
    'contact.submitError': 'Something went wrong sending your message. Please try again, or reach us directly using the contact details on this page.',
    'contact.getInTouch': 'Get in Touch',
    'contact.getInTouchBody': "Whether you're looking for information about our services, want to get involved, or need prayer, we're here for you. Don't hesitate to reach out!",
    'contact.addressLabel': 'Address',
    'contact.addressUnavailable': 'Address not available',
    'contact.phoneLabel': 'Phone',
    'contact.phoneUnavailable': 'Phone not available',
    'contact.emailLabel': 'Email',
    'contact.emailUnavailable': 'Email not available',
    'contact.officeHoursLabel': 'Office Hours',
    'contact.officeHoursUnavailable': 'Contact us for availability',
    'contact.quickActions': 'Quick Actions',
    'contact.scheduleMeeting': 'Schedule a Meeting',
    'contact.submitPrayerRequest': 'Submit Prayer Request',
    'contact.getDirections': 'Get Directions',
    'contact.joinWhatsApp': 'Join WhatsApp Group',
    'contact.ourStaff': 'Our Staff',
    'contact.ourStaffSubtitle': 'Meet our dedicated team who are here to serve you',
    'contact.faqHeading': 'Contact FAQ',
    'contact.findUs': 'Find Us',
    'contact.findUsSubtitle': 'Visit us at our location',
    'contact.category.spiritual': 'Spiritual & Community Life',
    'contact.category.administrative': 'Administrative & Facility',
    'contact.category.media': 'Media & Communication',
    'contact.category.outreach': 'Outreach & Missions',
    'contact.faq.responseTime.q': 'How quickly will I hear back?',
    'contact.faq.responseTime.a': 'It depends on the type of request — typically 1-5 business days. Prayer requests marked urgent or emergency are prioritized and answered as soon as possible.',
    'contact.faq.whoResponds.q': 'Who will respond to my message?',
    'contact.faq.whoResponds.a': 'Your message is routed based on the category you select, so it reaches the staff member or ministry team best equipped to help.',
    'contact.faq.urgent.q': 'What if my need is urgent?',
    'contact.faq.urgent.a': 'For a pastoral emergency, please call the church office directly rather than submitting the form — phone reaches us faster than email.',
    'contact.faq.visit.q': 'Can I just stop by instead of submitting a form?',
    'contact.faq.visit.a': "Absolutely — our office hours are listed on this page. You're always welcome to visit or call directly.",

    // Prayer page — TODO: verify translation
    'prayer.eyebrow': 'Prayer Wall',
    'prayer.title': 'Prayer Requests',
    'prayer.description': 'Share your prayer needs and join us in lifting each other up',
    'prayer.submitRequest': 'Submit Prayer Request',
    'prayer.wallTab': 'Prayer Wall',
    'prayer.answeredTab': 'Answered Prayers',
    'prayer.allPrayers': 'All Prayers',
    'prayer.category.healing': 'Healing',
    'prayer.category.guidance': 'Guidance',
    'prayer.category.thanksgiving': 'Thanksgiving',
    'prayer.category.family': 'Family',
    'prayer.category.work': 'Work',
    'prayer.category.general': 'General',
    'prayer.loading': 'Loading prayer requests...',
    'prayer.noAnsweredYet': 'No answered prayers yet',
    'prayer.noRequestsYet': 'No prayer requests yet',
    'prayer.checkBackAnswered': 'Check back soon to celebrate what God has done.',
    'prayer.submitToStart': 'Submit a prayer request to get started',
    'prayer.ongoing': 'Ongoing',
    'prayer.answered': 'Answered',
    'prayer.anonymous': 'Anonymous',
    'prayer.imPraying': "I'm Praying",
    'prayer.prayForThis': 'Pray for This',
    'prayer.prayed': 'prayed',
    'prayer.statRequests': 'Prayer Requests',
    'prayer.statPeople': 'People Praying',
    'prayer.statPrayers': 'Prayers Offered',
    'prayer.modalTitle': 'Submit Prayer Request',
    'prayer.prayerTitleLabel': 'Prayer Title',
    'prayer.prayerTitlePlaceholder': 'Enter a title for your prayer request',
    'prayer.requestLabel': 'Prayer Request',
    'prayer.requestPlaceholder': 'Share your prayer request...',
    'prayer.submitAnonymously': 'Submit anonymously',
    'prayer.yourNameOptional': 'Your name (optional)',
    'prayer.keepPrivate': 'Keep this prayer private (only pastors will see it)',
    'prayer.requestFollowUp': 'Request a private follow-up check-in in about a week',
    'prayer.emailForFollowUp': 'Your email for the follow-up',
    'prayer.cancel': 'Cancel',
    'prayer.submitPrayer': 'Submit Prayer',
    'prayer.powerOfPrayer': 'The Power of Prayer',
    'prayer.verseQuote': '"Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours."',
    'prayer.verseCitation': 'Mark 11:24',
    'prayer.powerBody': 'We believe in the power of prayer and the strength that comes from praying together as a community. Your prayers matter, and we are honored to lift each other up before God.',

    // Give page — TODO: verify translation
    'give.eyebrow': 'Generosity',
    'give.title': 'Give with Joy',
    'give.description': "Your generosity helps us serve our community and spread God's love",
    'give.waysToGive': 'Ways to Give',
    'give.waysToGiveSubtitle': "Online giving isn't available on the website yet. Here's how to give today:",
    'give.bankTransferTitle': 'Bank Transfer',
    'give.bankTransferBodyPrefix': 'Account details are available directly from the church office — please',
    'give.call': 'call',
    'give.or': 'or',
    'give.contactUs': 'contact us',
    'give.bankTransferBodySuffix': "and we'll share transfer instructions.",
    'give.inPersonTitle': 'In Person',
    'give.inPersonBody': 'Give during any of our worship services — see our current service times for when to join us.',
    'give.viewServiceTimes': 'View Service Times',
    'give.questionsTitle': 'Questions?',
    'give.questionsBody': 'Reach out about recurring gifts, planned/legacy giving, or designating a gift to a specific fund below.',
    'give.contactUsArrow': 'Contact Us',
    'give.designateHeading': 'You Can Designate Your Gift To',
    'give.designateSubtitle': 'Select a fund to see what to mention when you give.',
    'give.designateSelected': 'When you give, mention',
    'give.designateSelectedSuffix': 'so your gift is designated correctly.',
    'give.designateHint': "Just let us know which fund you'd like to support when you give in person or transfer a gift.",
    'give.fund.tithe.title': 'Tithe & Offerings',
    'give.fund.tithe.description': 'Regular giving to support our church ministries and operations',
    'give.fund.missions.title': 'Missions Fund',
    'give.fund.missions.description': 'Support our global mission work and local outreach programs',
    'give.fund.building.title': 'Building Fund',
    'give.fund.building.description': 'Help us maintain and improve our church facilities',
    'give.fund.special.title': 'Special Projects',
    'give.fund.special.description': 'Support specific ministry projects and community initiatives',
    'give.yourImpact': 'Your Impact',
    'give.yourImpactSubtitle': 'See how your generosity is making a difference in our community',
    'give.raisedThisYear': 'raised this year',
    'give.godsProvision': "God's provision",
    'give.impact.community.title': 'Community Outreach',
    'give.impact.community.description': 'Supporting families in need through food drives, counseling, and assistance programs.',
    'give.impact.missions.title': 'Global Missions',
    'give.impact.missions.description': 'Spreading the Gospel worldwide through missionary support and evangelism.',
    'give.impact.education.title': 'Education Ministry',
    'give.impact.education.description': 'Providing quality Christian education and scholarship programs.',
    'give.impact.youth.title': 'Youth Programs',
    'give.impact.youth.description': 'Investing in the next generation through camps, mentorship, and activities.',
    'give.transparencyHeading': 'Transparency Report',
    'give.transparencySubtitle': 'A look at how gifts are stewarded',
    'give.transparency.ministry': 'Ministry',
    'give.transparency.operations': 'Operations',
    'give.transparency.missions': 'Missions',
    'give.transparency.building': 'Building',
    'give.downloadAnnualReport': 'Download Annual Report',
    'give.whyWeGive': 'Why We Give',
    'give.why.worship.title': 'Worship Through Giving',
    'give.why.worship.description': 'Giving is an act of worship that acknowledges God as the source of all blessings.',
    'give.why.support.title': 'Support Our Mission',
    'give.why.support.description': 'Your gifts enable us to serve our community and spread the Gospel effectively.',
    'give.why.difference.title': 'Make a Difference',
    'give.why.difference.description': "Together, we can transform lives and communities through God's love and grace.",
    'give.verseQuote': '"Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver."',
    'give.verseCitation': '2 Corinthians 9:7',
    'give.faqHeading': 'Giving FAQ',
    'give.faq.receipt.q': 'Will I receive a giving receipt?',
    'give.faq.receipt.a': "Yes — contact the church office with your gift details and we'll provide a receipt for your records, including for tax purposes.",
    'give.faq.recurring.q': 'Can I set up recurring giving?',
    'give.faq.recurring.a': 'Yes, through a standing bank transfer instruction with your bank, or by arranging a recurring in-person gift with the church office. Ask us for guidance when you reach out.',
    'give.faq.designate.q': 'How do I make sure my gift goes to a specific fund?',
    'give.faq.designate.a': 'Select a fund below to see the name to reference, then mention it when you give in person or note it on your bank transfer.',
    'give.faq.method.q': "What's the difference between bank transfer and giving in person?",
    'give.faq.method.a': 'Both are fully counted the same way — bank transfer is convenient between services, while giving in person lets you use envelopes the office already tracks. Choose whichever is easiest for you.',
    'give.faq.legacy.q': 'What is planned or legacy giving?',
    'give.faq.legacy.aPrefix': 'A way to include the church in your will, trust, or beneficiary designations. See our',
    'give.faq.legacy.aLink': 'Legacy Giving page',
    'give.faq.legacy.aSuffix': 'for details.',
    'give.legacyTitle': 'Planned & Legacy Giving',
    'give.legacyBody': 'Include the church in your will, trust, or estate plans to leave a lasting legacy of generosity.',
    'give.learnAboutLegacy': 'Learn About Legacy Giving',
    'give.questionsAboutGiving': 'Questions About Giving?',
    'give.questionsAboutGivingBody': "We're here to help you with your generosity journey",
    'give.contactUsBtn': 'Contact Us',

    // About/Beliefs page — TODO: verify translation
    'about.eyebrow': 'About Us',
    'about.breadcrumbAbout': 'About',
    'about.breadcrumbBeliefs': 'Beliefs',
    'about.defaultTitle': 'Our Beliefs & About Us',
    'about.defaultSubtitle': 'Learn about our church family and what we believe',
    'about.nav.missionVision': 'Mission & Vision',
    'about.nav.coreValues': 'Core Values',
    'about.nav.whatWeBelieve': 'What We Believe',
    'about.nav.faq': 'FAQ',
    'about.ourMission': 'Our Mission',
    'about.defaultMission': 'To proclaim the Gospel of Jesus Christ, nurture believers through sound teaching, and build a community grounded in grace, faith, and love.',
    'about.ourVision': 'Our Vision',
    'about.defaultVision': 'To be a Christ-centered church that transforms lives and communities through faith, love, and service — equipping every believer to live with purpose.',
    'about.defaultCoreValues': 'Core Values',
    'about.defaultWhatWeBelieve': 'What We Believe',
    'about.guidingScripture': 'Guiding Scripture',
    'about.faqHeading': 'Frequently Asked Questions',
    'about.faq.visit.q': 'What should I expect when visiting for the first time?',
    'about.faq.visit.a': "A warm welcome, congregational singing, prayer, and expository preaching from Scripture. Services typically run about 90 minutes, and there's no dress code — come as you are.",
    'about.faq.baptism.q': 'Do you baptize infants or only believers?',
    'about.faq.baptism.a': "We practice believer's baptism by immersion, following a personal profession of faith, in keeping with our Primitive Baptist convictions.",
    'about.faq.children.q': 'Is there a place for my children during the service?',
    'about.faq.children.a': "Children are welcome to worship alongside their families. Reach out to a greeter when you arrive and they'll point you to any age-appropriate provisions we have that day.",
    'about.faq.membership.q': 'How can I become a member?',
    'about.faq.membership.a': "Membership follows a profession of faith and believer's baptism, along with meeting our pastors. Speak with one of our pastors after a service or use the Contact page to start the conversation."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<'en' | 'ta'>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as 'en' | 'ta';
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: 'en' | 'ta') => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}